.setcpu "65816"
.smart on

; ------------------------------------------------------------
; SNES PAL demo (LoROM):
; - Hardware-safe init sequence
; - Mode 1
; - BG1 only (4bpp, 8x8 tiles)
; - Full-screen 256x224 background from a JPG/PNG, generated by
;   tools/gen_assets.py's mode1_image target.
;
; Unlike main_mode5_4bpp.s (Mode 5 hi-res with 16x16 super-tiles),
; this target uses plain 8x8 BG1 tiles in Mode 1. 256x224 = 32x28 = 896
; cells, well within the 10-bit tilemap index budget (1024), so fully
; unique images fit on BG1 alone (flip-dedup is still applied to save
; CHR bytes).
;
; VRAM layout:
;   word $0000..$2FFF  BG1 tile data (4bpp, dense; up to 24 KiB)
;   word $3000..$33FF  BG1 tilemap   (2 KiB = 32x32 entries)
;
; The tilemap is placed at word $3000 (not $1000) on purpose: a 256x224
; background with mostly-unique tiles produces well over 2 KiB of tile
; data, so a tilemap at $1000 would land inside the tile region and the
; tilemap DMA would trash tile indices ~256..319. Moving the tilemap past
; the largest supported CHR blob (24 KiB = words $0000..$2FFF) keeps the
; two regions disjoint for every mode1_image asset set.
; ------------------------------------------------------------

INIDISP   = $2100
BGMODE    = $2105
BG1SC     = $2107
BG12NBA   = $210B
BG1HOFS   = $210D
BG1VOFS   = $210E
VMAIN     = $2115
VMADDL    = $2116
VMADDH    = $2117
VMDATAL   = $2118
VMDATAH   = $2119
CGADD     = $2121
CGDATA    = $2122
TM        = $212C
TS        = $212D
NMITIMEN  = $4200
WRIO      = $4201
MDMAEN    = $420B
HDMAEN    = $420C
MEMSEL    = $420D
APUIO0    = $2140
WMDATA    = $2180
WMADDL    = $2181
WMADDM    = $2182
WMADDH    = $2183

DMA0CTRL  = $4300
DMA0DEST  = $4301
DMA0SRC   = $4302
DMA0SRCB  = $4304
DMA0SIZE  = $4305

.segment "CODE"

Reset:
    sei
    clc
    xce                 ; native mode
    rep #$38            ; 16-bit A/X/Y
    ldx #$1FFF
    txs

    sep #$20
    lda #$80
    sta INIDISP         ; force blank

    stz NMITIMEN
    stz HDMAEN
    stz MDMAEN
    stz WRIO
    stz APUIO0
    stz APUIO0+1
    stz APUIO0+2
    stz APUIO0+3

    stz MEMSEL          ; SlowROM timing

    ; Clear WRAM (128 KiB) through $2180 via DMA fixed destination
    stz WMADDL
    stz WMADDM
    stz WMADDH
    lda #$08
    sta DMA0CTRL
    lda #$80            ; WMDATA
    sta DMA0DEST
    lda #<ZeroByte
    sta DMA0SRC
    lda #>ZeroByte
    sta DMA0SRC+1
    lda #^ZeroByte
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN
    lda #$01
    sta MDMAEN          ; second 64 KiB

    ; Clear VRAM (64 KiB) via $2118/$2119
    stz VMADDL
    stz VMADDH
    lda #$80
    sta VMAIN
    lda #$09            ; CPU->PPU, 2 regs write once, fixed source
    sta DMA0CTRL
    lda #$18
    sta DMA0DEST
    lda #<ZeroWord
    sta DMA0SRC
    lda #>ZeroWord
    sta DMA0SRC+1
    lda #^ZeroWord
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Clear CGRAM (512 bytes)
    stz CGADD
    lda #$08
    sta DMA0CTRL
    lda #$22            ; CGDATA
    sta DMA0DEST
    lda #<ZeroByte
    sta DMA0SRC
    lda #>ZeroByte
    sta DMA0SRC+1
    lda #^ZeroByte
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    lda #$02
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; PPU setup for Mode 1 (BG1/BG2 = 4bpp, BG3 = 2bpp), BG1 only.
    lda #$01
    sta BGMODE
    lda #$30            ; BG1 tilemap @ word $3000, 32x32
    sta BG1SC
    stz BG12NBA         ; BG1 4bpp tile base @ VRAM word $0000
    stz BG1HOFS
    stz BG1HOFS
    stz BG1VOFS
    stz BG1VOFS

    ; Upload BG1 palette (16 colors = 32 bytes) to CGRAM $00..$1F
    stz CGADD
    lda #$00
    sta DMA0CTRL
    lda #$22
    sta DMA0DEST
    lda #<PaletteData
    sta DMA0SRC
    lda #>PaletteData
    sta DMA0SRC+1
    lda #^PaletteData
    sta DMA0SRCB
    lda #$20
    sta DMA0SIZE
    stz DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Upload BG1 tiles. Size = (TileDataEnd - TileData), emitted dense by
    ; gen_assets mode1_image and rewritten for every image.
    stz VMADDL
    stz VMADDH
    lda #$80
    sta VMAIN
    lda #$01
    sta DMA0CTRL
    lda #$18
    sta DMA0DEST
    lda #<TileData
    sta DMA0SRC
    lda #>TileData
    sta DMA0SRC+1
    lda #^TileData
    sta DMA0SRCB
    lda #<(TileDataEnd - TileData)
    sta DMA0SIZE
    lda #>(TileDataEnd - TileData)
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Upload 32x32 tilemap (2048 bytes) at VRAM word $3000
    lda #$00
    sta VMADDL
    lda #$30
    sta VMADDH
    lda #$80
    sta VMAIN
    lda #$01
    sta DMA0CTRL
    lda #$18
    sta DMA0DEST
    lda #<TilemapData
    sta DMA0SRC
    lda #>TilemapData
    sta DMA0SRC+1
    lda #^TilemapData
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    lda #$08
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    lda #$01            ; BG1 on main screen
    sta TM
    stz TS

    lda #$0F
    sta INIDISP         ; end force blank, full brightness

Forever:
    wai
    bra Forever

Nmi:
    rti

Irq:
    rti

.segment "RODATA"

ZeroByte:
    .byte $00
ZeroWord:
    .word $0000

; Asset paths use the `mode1_image` default --name. Generate them with:
;   python3 tools/gen_assets.py mode1_image --source YOUR.png --bpp 4
; (see README.md section "Full-screen image pipelines" for details).
PaletteData:
    .incbin "build/mode1_image/palette.bin"

TileData:
    .incbin "build/mode1_image/tiles.4bpp.chr"
TileDataEnd:

TilemapData:
    .incbin "build/mode1_image/tilemap.bin"

.segment "HEADER"
    ; 21-byte internal title
    .byte "MODE1 IMG PAL DEMO   "
    .byte $20, $00, $05, $00
    .byte $02
    .byte $00, $00
    .word $0000
    .word $0000

.segment "VECTORS"
    .word $0000          ; $FFE0 Native reserved
    .word $0000          ; $FFE2 Native reserved
    .word $0000          ; $FFE4 Native COP
    .word $0000          ; $FFE6 Native BRK
    .word $0000          ; $FFE8 Native ABORT
    .word Nmi            ; $FFEA Native NMI
    .word $0000          ; $FFEC Native reserved (no native RESET)
    .word Irq            ; $FFEE Native IRQ
    .word $0000          ; $FFF0 Emu reserved
    .word $0000          ; $FFF2 Emu reserved
    .word $0000          ; $FFF4 Emu COP
    .word $0000          ; $FFF6 Emu reserved
    .word $0000          ; $FFF8 Emu ABORT
    .word $0000          ; $FFFA Emu NMI
    .word Reset          ; $FFFC Emu RESET
    .word $0000          ; $FFFE Emu IRQ/BRK
