.setcpu "65816"
.smart on

; ------------------------------------------------------------
; SNES PAL demo (LoROM):
; - Hardware-safe init sequence
; - Mode 5 (BG1 = 4bpp, BG2 = 2bpp), interlace on
; - BG1 only, configured with 16x16 tile size (BGMODE bit 4)
; - Displays a full-screen 512x448 wallpaper generated by
;   tools/gen_assets.py's mode5_image target (--name mode5_wallpaper_4bpp).
;
; This is the 4bpp counterpart of main_mode5_2bpp.s. Instead of four
; corner characters on a blank BG2, the whole 32x28 visible super-tile
; grid is filled with the dense-packed, flip-dedup'd BG1 tileset
; produced from assets/linux_wallpaper_512x448_right_4bpp.png.
;
; Notes on Mode 5 specifics:
; - Mode 5 is inherently horizontal hi-res (512 px wide). Main-screen
;   pixels fill the odd columns, sub-screen pixels fill the even columns,
;   so a BG layer must be enabled on BOTH TM and TS to cover the full
;   width; otherwise only half the content (every other column) is visible.
; - Interlace (SETINI bit 0) doubles vertical resolution to 448 lines by
;   alternating odd/even scanlines per field.
; - BG1 is 4bpp in Mode 5 with sub-palette 0 at CGRAM $00..$1F.
; - With BGMODE bit 4 set, BG1 runs in 16x16 tile mode: one tilemap entry
;   selects four consecutive 8x8 VRAM tiles (N, N+1, N+16, N+17). The
;   image's 32x28 = 896 super-tiles are flip-dedup'd and dense-packed so
;   the 10-bit tilemap index budget is not exceeded.
;
; VRAM layout:
;   word $0000..$2FFF  BG1 tile data (24 KiB = 768 8x8 4bpp tiles)
;   word $3000..$33FF  BG1 tilemap   (2 KiB = 32x32 entries)
;
; If gen_assets.py ever emits a different tile count, update BG1SC and
; the TileData DMA size (DMA0SIZE) in lockstep. Current value: $6000 bytes.
; ------------------------------------------------------------

INIDISP   = $2100
BGMODE    = $2105
BG1SC     = $2107
BG12NBA   = $210B
BG1HOFS   = $210D
BG1VOFS   = $210E
VMAIN     = $2115
VMADDL    = $2116
VMADDH    = $2117
VMDATAL   = $2118
VMDATAH   = $2119
CGADD     = $2121
CGDATA    = $2122
TM        = $212C
TS        = $212D
TMW       = $212E
TSW       = $212F
CGWSEL    = $2130
CGADSUB   = $2131
SETINI    = $2133
NMITIMEN  = $4200
WRIO      = $4201
MDMAEN    = $420B
HDMAEN    = $420C
MEMSEL    = $420D
APUIO0    = $2140
WMDATA    = $2180
WMADDL    = $2181
WMADDM    = $2182
WMADDH    = $2183

DMA0CTRL  = $4300
DMA0DEST  = $4301
DMA0SRC   = $4302
DMA0SRCB  = $4304
DMA0SIZE  = $4305

.segment "CODE"

Reset:
    sei
    clc
    xce                 ; native mode
    rep #$38            ; 16-bit A/X/Y
    ldx #$1FFF
    txs

    ; Force blank, full brightness later after setup
    sep #$20
    lda #$80
    sta INIDISP

    stz NMITIMEN
    stz HDMAEN
    stz MDMAEN
    stz WRIO
    stz APUIO0
    stz APUIO0+1
    stz APUIO0+2
    stz APUIO0+3

    ; SlowROM timing (compatible baseline)
    stz MEMSEL

    ; Clear WRAM (128 KiB) through $2180 data port via DMA fixed destination
    stz WMADDL
    stz WMADDM
    stz WMADDH

    lda #$08            ; CPU->PPU, fixed destination
    sta DMA0CTRL
    lda #$80            ; WMDATA
    sta DMA0DEST
    lda #<ZeroByte
    sta DMA0SRC
    lda #>ZeroByte
    sta DMA0SRC+1
    lda #^ZeroByte
    sta DMA0SRCB
    lda #$00            ; 0 means 65536 bytes
    sta DMA0SIZE
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN
    lda #$01
    sta MDMAEN          ; second 64 KiB

    ; Clear VRAM (64 KiB) with zero through $2118/$2119
    stz VMADDL
    stz VMADDH
    lda #$80            ; increment after writing high byte, +1 word
    sta VMAIN
    lda #$09            ; CPU->PPU, 2 regs write once ($2118 then $2119), fixed source
    sta DMA0CTRL
    lda #$18            ; VMDATAL
    sta DMA0DEST
    lda #<ZeroWord
    sta DMA0SRC
    lda #>ZeroWord
    sta DMA0SRC+1
    lda #^ZeroWord
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Clear CGRAM (512 bytes)
    stz CGADD
    lda #$08            ; CPU->PPU fixed destination
    sta DMA0CTRL
    lda #$22            ; CGDATA
    sta DMA0DEST
    lda #<ZeroByte
    sta DMA0SRC
    lda #>ZeroByte
    sta DMA0SRC+1
    lda #^ZeroByte
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    lda #$02
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; PPU setup for Mode 5. BGMODE layout:
    ;   bits 0..2 = mode    -> $05 (mode 5: BG1 4bpp, BG2 2bpp, hi-res)
    ;   bit 4     = BG1 tile size 16x16 (0=8x8, 1=16x16)
    ; => $05 | $10 = $15. BG2 stays at 8x8 but is not used.
    lda #$15
    sta BGMODE

    ; BG1SC: top 6 bits = tilemap VRAM base (in 1K-word steps), low 2 bits = size.
    ; Tilemap uploaded at word $3000 => base index 12 => register value $30.
    ; Low 2 bits = 0 means 32x32 tilemap.
    lda #$30            ; BG1 tilemap @ word $3000, 32x32
    sta BG1SC

    ; BG12NBA: low nibble = BG1 char base (word / $1000),
    ;          high nibble = BG2 char base.
    ; We only use BG1; tiles live at VRAM word $0000 => both nibbles 0.
    stz BG12NBA
    stz BG1HOFS
    stz BG1HOFS
    stz BG1VOFS
    stz BG1VOFS

    ; Enable interlace (SETINI bit 0). Vertical resolution doubles from
    ; 224 to 448 lines; the PPU alternates odd/even scanline fields.
    lda #$01
    sta SETINI

    ; Upload BG1 sub-palette 0 (4bpp = 16-color palette = 32 bytes) to CGRAM
    ; $00..$1F. Tilemap entries for this demo use palette-field 0.
    stz CGADD
    lda #$00
    sta DMA0CTRL
    lda #$22            ; CGDATA
    sta DMA0DEST
    lda #<PaletteData
    sta DMA0SRC
    lda #>PaletteData
    sta DMA0SRC+1
    lda #^PaletteData
    sta DMA0SRCB
    lda #$20            ; 32 bytes = 16 colors
    sta DMA0SIZE
    stz DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Upload BG1 tiles: 4bpp, dense-packed by gen_assets mode5_image.
    ; Currently 768 8x8 tiles * 32 bytes/tile = 24576 bytes = $6000,
    ; occupying VRAM words $0000..$2FFF. If the tile count changes, this
    ; DMA size and the BG1SC/tilemap base above must move in lockstep.
    stz VMADDL
    stz VMADDH
    lda #$80            ; increment after VMDATAH write, +1 word
    sta VMAIN
    lda #$01            ; CPU->PPU, destination increments
    sta DMA0CTRL
    lda #$18            ; VMDATAL
    sta DMA0DEST
    lda #<TileData
    sta DMA0SRC
    lda #>TileData
    sta DMA0SRC+1
    lda #^TileData
    sta DMA0SRCB
    lda #$00            ; 24576 bytes = $6000
    sta DMA0SIZE
    lda #$60
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; Upload full 32x32 tilemap (2048 bytes) at VRAM word $3000.
    ; With 16x16 tile size each entry spans a 16x16 screen region;
    ; 32 columns x 28 rows cover the 512x448 visible image. The four
    ; off-screen rows (y >= 28) are filled with a reserved blank
    ; super-tile that sits right after the last unique one.
    lda #$00
    sta VMADDL
    lda #$30
    sta VMADDH
    lda #$80
    sta VMAIN
    lda #$01
    sta DMA0CTRL
    lda #$18
    sta DMA0DEST
    lda #<TilemapData
    sta DMA0SRC
    lda #>TilemapData
    sta DMA0SRC+1
    lda #^TilemapData
    sta DMA0SRCB
    lda #$00
    sta DMA0SIZE
    lda #$08            ; 2048 bytes
    sta DMA0SIZE+1
    lda #$01
    sta MDMAEN

    ; In Mode 5 hi-res the main screen supplies odd columns and the sub
    ; screen supplies even columns. Enable BG1 on BOTH layers, otherwise
    ; only every second column of the wallpaper is visible.
    lda #$01            ; BG1 on main screen
    sta TM
    lda #$01            ; BG1 on sub screen
    sta TS
    ; Real hardware leaves these registers undefined; bsnes initialises all
    ; to 0. In Mode 5 with TM=TS=$01 (BG1 on both screens) they are
    ; load-bearing: CGADSUB bit7=1 + bit0=1 cancels BG1 to black, and
    ; TMW/TSW bit0=1 window-masks BG1 off the screen entirely.
    stz TMW             ; no window masking on main screen
    stz TSW             ; no window masking on sub  screen
    stz CGWSEL          ; no color-math windowing
    stz CGADSUB         ; no color math (addition / subtraction)
    stz $2123           ; W12SEL: no BG1/BG2 window enables
    stz $2124           ; W34SEL: no BG3/BG4 window enables

    ; End force blank, brightness max
    lda #$0F
    sta INIDISP

Forever:
    wai
    bra Forever

Nmi:
    rti

Irq:
    rti

.segment "RODATA"

ZeroByte:
    .byte $00
ZeroWord:
    .word $0000

PaletteData:
    .incbin "build/mode5_wallpaper_4bpp/palette.bin"

TileData:
    .incbin "build/mode5_wallpaper_4bpp/tiles.4bpp.chr"

TilemapData:
    .incbin "build/mode5_wallpaper_4bpp/tilemap.bin"

.segment "HEADER"
    ; 21-byte internal title
    .byte "MODE5 4BPP PAL WALL  "
    ; map mode, cart type, ROM size, SRAM size
    ; ROM size $08 required for Everdrive LoROM mapping: $05 (= 32 KiB per
    ; SNES spec) makes Everdrive map the ROM as "8m" at the wrong address;
    ; $08 selects the "512k" mapping that mirrors 32 KiB correctly.
    ; The S-CPU itself ignores this field.
    .byte $20, $00, $08, $00
    ; destination code: $02 = Europe (PAL)
    .byte $02
    ; fixed value + version. $00 = old-style header (no extended header at
    ; $FFB0-$FFBF). $33 would claim an extended header, which we do not ship.
    .byte $00, $00
    ; complement and checksum (fix_checksum.py rewrites these post-link)
    .word $0000
    .word $0000

.segment "VECTORS"
    ; $FFE0-$FFFF vector table layout. Only $FFFC (Emu RESET) is actually
    ; fetched by the CPU on power-on; native RESET does not exist.
    .word $0000          ; $FFE0 Native reserved
    .word $0000          ; $FFE2 Native reserved
    .word $0000          ; $FFE4 Native COP
    .word $0000          ; $FFE6 Native BRK
    .word $0000          ; $FFE8 Native ABORT
    .word Nmi            ; $FFEA Native NMI
    .word $0000          ; $FFEC Native reserved (no native RESET)
    .word Irq            ; $FFEE Native IRQ
    .word $0000          ; $FFF0 Emu reserved
    .word $0000          ; $FFF2 Emu reserved
    .word $0000          ; $FFF4 Emu COP
    .word $0000          ; $FFF6 Emu reserved
    .word $0000          ; $FFF8 Emu ABORT
    .word $0000          ; $FFFA Emu NMI
    .word Reset          ; $FFFC Emu RESET
    .word $0000          ; $FFFE Emu IRQ/BRK
